# deployment.yaml
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: LoadBalancer  # Change the type to LoadBalancer
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80         # Port exposed by the Load Balancer (http default)
      targetPort: 5000 # Port your Flask app is listening on
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app-container
          image: shaked0703/docflask2:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
