version: '3'
services:
  web:
    build: .
    image: liorfizz/alpaca
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - redis
  redis:
    image: redis:alpine
    volumes:
      - db-data:/data
volumes:
  db-data:
