version: '3'
services:
  web:
    image: shaked0703/docflask2
    ports:
      - '5000:5000'
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
